<?php if (!defined('FW')) die('Forbidden');

class FW_Extension_Page_Builder extends FW_Extension
{
	private $builder_option_key    = 'page-builder';
	private $supports_feature_name = 'fw-page-builder';

	private $shortcode_atts_coder;

	public function get_supports_feature_name()
	{
		return $this->supports_feature_name;
	}

	/**
	 * @internal
	 */
	protected function _init()
	{
		if (is_admin()) {
			$this->check_for_builder_modal_ajax();
			$this->add_admin_filters();
			$this->add_admin_actions();
		} else {
			$this->shortcode_atts_coder = new _FW_Ext_Page_Builder_Shortcode_Atts_Coder();
			$this->add_theme_filters();
		}
	}

	/*
	 * when a builder modal window draws or saves
	 * options the shortcodes must be loaded
	 * because they may load their own custom option types
	 */
	private function check_for_builder_modal_ajax()
	{
		if (
			defined('DOING_AJAX') &&
			DOING_AJAX === true   &&
			(
				FW_Request::POST('action', '') === 'fw_backend_options_render' ||
				FW_Request::POST('action', '') === 'fw_backend_options_get_values'
			)
		) {
			$this->get_parent()->load_shortcodes();
		}
	}

	private function add_admin_filters()
	{
		add_filter('fw_post_options', array($this, '_admin_filter_fw_post_options'), 10, 2);
	}

	private function add_admin_actions()
	{
		add_action('fw_save_post_options', array($this, '_admin_action_fw_save_post_options'), 10, 2);
	}

	private function add_theme_filters()
	{
		add_filter('fw_shortcode_atts', array($this, '_theme_filter_fw_shortcode_atts'));
		add_action('the_content', array($this, '_theme_filter_prevent_autop'), 1);
	}

	/*
	 * Adds the page builder metabox if the $post_type is supported
	 * @internal
	 */
	public function _admin_filter_fw_post_options($post_options, $post_type)
	{
		if ( post_type_supports( $post_type, $this->supports_feature_name ) ) {
			$this->get_parent()->load_shortcodes();
			$page_builder_options = array(
				'page-builder-box' => array(
					'title' => false,
					'type' => 'box',
					'priority' => 'high',
					'options' => array(
						$this->builder_option_key => array(
							'label' => false,
							'desc' => false,
							'type' => 'page-builder',
							'editor_integration' => true
						)
					)
				)
			);
			$post_options = array_merge($page_builder_options, $post_options);
		}

		return $post_options;
	}

	/**
	 * @internal
	 */
	public function _admin_action_fw_save_post_options($post_id, $post)
	{
		if ( post_type_supports( $post->post_type, $this->supports_feature_name ) ) {
			$builder_shortcodes = fw_get_db_post_option($post_id, $this->builder_option_key);
			if (
				!$builder_shortcodes['builder_active'] ||
				!$builder_shortcodes['shortcode_notation']
			) {
				return;
			}

			// remove then add again to avoid infinite loop
			remove_action('fw_save_post_options', array($this, '_admin_action_fw_save_post_options'));
			wp_update_post(array(
				'ID' => $post_id,
				'post_content' => str_replace('\\', '\\\\\\\\\\', $builder_shortcodes['shortcode_notation'])
			));
			add_action('fw_save_post_options', array($this, '_admin_action_fw_save_post_options'), 10, 2);
		}
	}

	/**
	 * @internal
	 */
	public function _theme_filter_fw_shortcode_atts($atts)
	{
		return $this->shortcode_atts_coder->decode_atts($atts);
	}

	/**
	 * @internal
	 */
	public function _theme_filter_prevent_autop($content)
	{
		if ($this->is_builder_post()) {

			/**
			 * Wrap the content in a div to prevent wpautop change/break the html generated by the shortcodes
			 */
			return
				'<div class="'. esc_attr(apply_filters('fw_ext_page_builder_content_wrapper_class', 'fw-page-builder-content')) .'">' .
					$content .
				'</div>';
		}

		return $content;
	}

	/**
	 * Checks if a post was built with builder
	 */
	public function is_builder_post($post_id = '')
	{
		if (!$post_id) {
			global $post;
		} else {
			$post = get_post($post_id);
		}

		if (!$post) {
			return false;
		}

		if ( post_type_supports( $post->post_type, $this->supports_feature_name ) ) {
			return (bool) fw_get_db_post_option($post->ID, $this->builder_option_key .'/builder_active');
		} else {
			return false;
		}
	}
}
